website/auth.py
## this manages database and tickets

from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from .models import Customer, Ticket, Lot, User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash # this is used for login credential, hashing and stuff
from random import randint
from flask_login import login_user, login_required, logout_user, current_user

import mercadopago

auth = Blueprint('auth', __name__)

# get lot by lot_id
def get_lot(lot_id):
    my_lot = db.session.execute(db.select(Lot).filter_by(id=lot_id)).scalar()

    if my_lot:
        lot_res = {
            'prize': my_lot.prize,          # description of the product
            't_price': my_lot.t_price       # price of ticket
        }
        
        return lot_res
    else:
        return None 

def check_tick(lot_id):
    tick_db = db.session.execute(db.select(Ticket).filter_by(lot_id=lot_id)).scalars()
    tick_array = []

    # get all tickets from a lot in array form
    for row in tick_db:
        tick_array.append(row.tick)

    # check if there's any tickets left
    if len(tick_array) == 10000:
        flash("Ya no hay más boletas")
        return False
    else:
        return True
        
def get_ticket(user, lot_id):
    tick_db = db.session.execute(db.select(Ticket).filter_by(lot_id=lot_id)).scalars()
    tick_array = []

    # get all tickets from a lot in array form
    for row in tick_db:
        tick_array.append(row.tick)

    # check if there's any tickets left
    if len(tick_array) == 10000:
        flash("Ya no hay más boletas")
        return None

    # sort list
    tick_array.sort()

    # generates a random new_tick_num and searchs in
    # the array if it exists already
    new_tick_num = randint(0, 9999)
    while new_tick_num in tick_array:
        new_tick_num = randint(0, 9999)

    new_tick = Ticket(user_id=user.id, lot_id=lot_id, tick=new_tick_num)
    
    return new_tick


@auth.route('/consultar', methods=['GET', 'POST'])
def consultar():
    if request.method == 'POST':
        # query SELECT * FROM User, Ticket WHERE User.id == Ticket.user_id AND User.email == email 
        email = request.form.get('email')
        db_search = db.session.execute(db.select(Customer, Ticket).filter(Customer.id == Ticket.user_id).where(Customer.email==email))
        
        if not db_search:
            return render_template('check.html')
        else:
            return render_template('check.html', db_search=db_search)
        
    return render_template('check.html')


    # check if there's any tickets left
    if len(tick_array) == 10000:
        flash("Ya no hay más boletas")
        return None

    # sort list because why not
    tick_array.sort()

    # generates a random new_tick_num and searchs in
    # the array if it exists already
    new_tick_num = randint(0, 9999)
    while new_tick_num in tick_array:
        new_tick_num = randint(0, 9999)

    new_tick = Ticket(user_id=user.id, lot_id=lot_id, tick=new_tick_num)
    
    return new_tick


# writes contact info in data base db
def finish_payment(email, name, contact, lot_id):
    # database entries
    new_user = Customer(email=email, name=name, contact=contact)

    # user conf load
    db.session.add(new_user)
    
    for i in range(int(session['ticks'])):
        new_ticket = get_ticket(new_user, lot_id)
        db.session.add(new_ticket)

    # commit to db
    db.session.commit() 

    flash('Compra exitosa!', category='success')
    return redirect(url_for('views.home'))



## ------------
## PORTAL ADMIN
##-------------
##  HOW TO CREATE AN ADMIN ACCOUNT:
#   ---- DATABASE ----
#   new_admin = User(login="Login-name-here", passwd=generate_password_hash("password-here", method='pbkdf2:sha256'))
#   db.session.add(new_admin)
#   db.session.commit()


@auth.route('/admin-login', methods=['GET', 'POST'])
def admin_login():
#    the example above goes here, maybe idk
    if request.method == 'POST':
        login = request.form.get('login')
        passwd = request.form.get('passwd')

        # authentication of admin login
        admin_db = db.session.execute(db.select(User).where(User.login==login)).scalar()
        print(admin_db.passwd)
        if admin_db:
            if check_password_hash(admin_db.passwd, passwd):
                flash('Welcome', category='success')
                login_user(admin_db, remember=True)
                return redirect(url_for('auth.admin'))
            else:
                flash('Error: credenciales incorrectas', category='error')
        else:
            flash('Error: el admin no existe', category='error')

    return render_template('admin-login.html')

# logout
@auth.route('/admin-logout')
@login_required
def admin_logout():
    logout_user()
    return redirect(url_for('auth.admin_login'))

# admin view
@auth.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():

    if request.method == 'POST':
        # Crea un sorteo nuevo
        # makes new lottery
        lot = request.form.get('lot')
        t_price = request.form.get('t_price')
        new_lot = Lot(prize=lot, t_price=t_price)
        db.session.add(new_lot)
        db.session.commit()

    # query all data to display
    users = db.session.execute(db.select(Customer).order_by(Customer.id)).scalars()
    lots = db.session.execute(db.select(Lot).order_by(Lot.id)).scalars()
    tickets = db.session.execute(db.select(Ticket).order_by(Ticket.id)).scalars()
    tickets = db.session.execute(db.select(Ticket).order_by(Ticket.id)).scalars()
    admins = db.session.execute(db.select(User).order_by(User.id)).scalars()

    return render_template('admin.html', users=users, lots=lots, tickets=tickets, admins=admins)
    

website/templates/admin-login.html
{% extends "base.html" %}

{% block title %}
    Admin-login
{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST">
            <div class="form-group">
                Login: <input type="text" class="form-control" id="login" name="login" placeholder="Nombre de usuario" >
            </div>
            <div class="form-group">
                Contraseña: <input type="password" class="form-control" id="password" name="passwd" placeholder="Contraseña" >
            </div>    
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
{% endblock %}

website/templates/admin.html
{% extends "base.html" %}

{% block title %}
    Admin
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <form action={{ url_for('auth.admin_logout') }}>
            <input type="submit" class="btn btn-primary" value="Cerrar sesion" />
        </form>
    </div>

    <div class="container mt-2 mb-2">
        <form method="POST">
            <h3 align="center">Crear Sorteo</h3>
            <div class="form-group">
                <label for="lot">
                Sorteo
                </label>
                <input 
                    type="text" 
                    class="form-control" 
                    id="lot" 
                    name="lot" 
                    placeholder="Descripcion de sorteo"
                />
            </div>
            <div class="form-group">
                <label for="lot">
                Precio
                </label>
                <input 
                    type="number" 
                    class="form-control" 
                    id="t_price" 
                    name="t_price" 
                    placeholder="Precio de boleta"
                />
            </div>
            
            <br />
            <button type="submit" class="btn btn-primary">Ingresar</button>
        </form>
    </div>

    <div class="container">

        <h2>Usuarios</h2>
        <p>Formato: id -- nombre -- email</p>
        {% for user in users %}
            <p>{{ user.id }} -- {{ user.name }} -- {{ user.email }}</p>
        {% endfor %}
            <h2>Sorteos</h2>
            <p>Formato: id -- precio de boleta -- descripción del premio </p>
        {% for lot in lots %}
            <p>{{ lot.id }} -- {{ lot.t_price }} -- {{ lot.prize }} -- {{ lot.t_price }}</p>
        {% endfor %}
            <h2>Boletas</h2>
            <p>Formato: id -- id de comprador -- id de sorteo -- numero de boleta/p>
        {% for ticket in tickets %}
            <p>{{ ticket.id }} -- {{ ticket.user_id }} -- {{ ticket.lot_id }} -- {{ ticket.tick }} </p>
        {% endfor %}
            <h2>ADMINISTRADORES</h2>
            <p>Formato: id -- administrador</p>
        {% for ad in admins %}
            <p>{{ ad.id }} -- {{ ad.login }} </p>
        {% endfor %}
    
    </div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous"
        />
        <script src="https://sdk.mercadopago.com/js/v2">
        </script>

        <title>{% block title %}Home{% endblock %}</title>
    </head>
    <body class="bg-dark text-light">
      <div class="d-flex flex-column min-vh-100">
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbar"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
              <div class="navbar-nav">
                <a class="nav-item nav-link" id="home" href="/">Inicio</a>
                <!-- <a class="nav-item nav-link" id="logout" href="/boletas">Comprar Boleta</a> -->
                <a class="nav-item nav-link" id="ticket_search" href="/consultar">Consultar numero</a>
              </div>
              
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% elif category == 'message' %}
                        <div class="alert alert-info fade show" role="alert">
                          {{ message }}
                          <button type="button" class="close" data-dismiss="alert">
                              <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                    {% else %}
                        <div class="alert alert-success fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}                                        
                {% endfor %}
            {% endif%}
        {% endwith %}

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="navbar-dark bg-secondary mt-auto footer pt-2 pb-1">
          <div class="container">
              <p class="text-center">Contacto:   
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
                  <path d="M13.601 2.326A7.85 7.85 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.9 7.9 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.9 7.9 0 0 0 13.6 2.326zM7.994 14.521a6.6 6.6 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.56 6.56 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592m3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.73.73 0 0 0-.529.247c-.182.198-.691.677-.691 1.654s.71 1.916.81 2.049c.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232"/>
                </svg>
                3021223344 -- Correo: motos@lorem.ipsum
              </p>
          </div>
        </footer>
      </div>
        <!-- bootstrap cdn -->
        <script
          src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"
        ></script>

        <!-- mercadopago cdn -->
        <script src="https://sdk.mercadopago.com/js/v2"></script>
    </body>
</html>

website/templates/check.html
{% extends "base.html" %}

{% block title %}
    Consultar Numero
{% endblock %}

{% block content %}
    <form method="POST">
        <h3 align="center" class="container mt-5">Chequea tus boletas</h3>
        <div class="form-group">
            <label for="email">
                Correo Electronico
            </label>
            <input 
                type="email" 
                class="form-control" 
                id="email" 
                name="email" 
                placeholder="Ingresa el correo"
            />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Chequear</button>
    </form>
    <div class="container-fluid mt-4 ml-3">
        {% for row in db_search %}
            <p>{{ row.Ticket.tick }}</p>
        {% endfor %}
    </div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block title %}
    Inicio
{% endblock %}

{% block content %}
<h1 align="center" class="mt-5 mb-5">TITULO VA AQUI</h1>
<!-- CONTAINER -- 2 FOR EACH ROW -->
    <div class="container">

        <div class="row">
            <div class="col-lg">
                <a href="{{ url_for('pse.pse_payment', lot_id=1) }}" 
                    type="submit" 
                    name="lot_3" 
                    id="lot_3">
                    <!-- boton para seleccionar tiquete -->
                    <img src="/static/horse_picture.png"
                        class="w-100 shadow-1-strong rounded mb-4"
                        alt="Boleta 2"
                        id="lot_2"
                    >  
                </a>
            </div>

            <div class="col-lg">
                <a href="{{ url_for('pse.pse_payment', lot_id=2) }}" 
                    type="submit" 
                    name="lot_3" 
                    id="lot_3">
                    <!-- boton para seleccionar tiquete -->
                    <img src="/static/horse_picture.png"
                        class="w-100 shadow-1-strong rounded mb-4"
                        alt="Boleta 2"
                        id="lot_2"
                    >  
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-lg">
                <a href="{{ url_for('pse.pse_payment', lot_id=3) }}" 
                    type="submit" 
                    name="lot_3" 
                    id="lot_3">
                    <!-- boton para seleccionar tiquete -->
                    <img src="/static/horse_picture.png"
                        class="w-100 shadow-1-strong rounded mb-4"
                        alt="Boleta 2"
                        id="lot_2"
                    >  
                </a>
            </div>

            <div class="col-lg">
                <a href="{{ url_for('pse.pse_payment', lot_id=4) }}" 
                    type="submit" 
                    name="lot_3" 
                    id="lot_3">
                    <!-- boton para seleccionar tiquete -->
                    <img src="/static/horse_picture.png"
                        class="w-100 shadow-1-strong rounded mb-4"
                        alt="Boleta 2"
                        id="lot_2"
                    >  
                </a>
            </div>

        </div>
    </div>
        <script src="https://sdk.mercadopago.com/js/v2">
            window.paymentBrickController.unmount()
        </script>
{% endblock %}

            <!--
            <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">

                <div>
                    <a href="{{ url_for('pse.pse_payment', lot_id=1) }}" 
                        type="submit" 
                        name="lot_1" 
                        id="lot_1">
                        
                        <p>yee</p>
                        <img src="/static/horse_picture.png"
                            class="w-100 shadow-1-strong rounded mb-4"
                            alt="Boleta 1"
                            id="lot_1"
                        >  
                    </a>
                </div>

                <div>
                    <a href="{{ url_for('pse.pse_payment', lot_id=2) }}" 
                        type="submit" 
                        name="lot_2" 
                        id="lot_2">
                    
                        <p>yee</p>
                        <img src="/static/horse_picture.png"
                            class="w-100 shadow-1-strong rounded mb-4"
                            alt="Boleta 2"
                            id="lot_2"
                        >  
                    </a>
                </div>

              
            </div>

            <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
            
            </div>
        -->

website/templates/pse_form.html
{% extends "base.html" %}

{% block title %}
Pago PSE
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h3>Ingresa tus datos</h3>
</div>
<div class="container">
    <h4>Pago por PSE</h4>
</div>
<div class="container mt-5">
    <form id="form-checkout" method="POST">
        <div class="btn-group btn-group-toggle mb-2" data-toggle="buttons">
            <label class="btn btn-secondary active">
                <input type="radio" name="options" id="2" value="2" autocomplete="off" checked="checked" />2 Boletas
            </label>

            <label class="btn btn-secondary">
                <input type="radio" name="options" id="5" value="5" autocomplete="off" /> 5 Boletas
            </label>

            <label class="btn btn-secondary">
                <input type="radio" name="options" id="10" value="10" autocomplete="off" /> 10 Boletas
            </label>

            <label class="btn btn-secondary">
                <input type="radio" name="options" id="20" value="20" autocomplete="off" /> 20 Boletas
            </label>
        </div>
        <!--
        <div class="form-group">
            <label for="zipCode">Codigo Postal</label>
            <input id="form-checkout__zipCode" name="zipCode" type="text" class="form-control">
        </div>

        <div class="form-group">
            <label for="streetName">Street Name</label>
            <input id="form-checkout__streetName" name="streetName" type="text" class="form-control">
        </div>

        <div class="form-group">
            <label for="streetNumber">Street Number</label>
            <input id="form-checkout__streetNumber" name="streetNumber" type="text" class="form-control">
        </div>

        <div class="form-group">
            <label for="neighborhood">Neighborhood</label>
            <input id="form-checkout__neighborhood" name="neighborhood" type="text" class="form-control">
        </div>

        <div class="form-group">
            <label for="city">Ciudad</label>
            <input id="form-checkout__city" name="city" type="text" class="form-control">
        </div class="form-group">

        <div class="form-group">
            <label for="phoneAreaCode">PhoneAreaCode</label>
            <input id="form-checkout__phoneAreaCode" name="phoneAreaCode" type="text" class="form-control">
        </div>

        <div class="form-group">
            <label for="phoneNumber">PhoneNumber</label>
            <input id="form-checkout__phoneNumber" name="phoneNumber" type="text" class="form-control">
        </div>
        -->
        <div class="form-group">
            <label for="name">Nombre</label>
            <input id="form-checkout__name" name="name" type="text" class="form-control" placeholder="Nombre Completo">
        </div>
        <div class="form-group">
            <label for="email">Correo Electronico</label>
            <input id="form-checkout__email" name="email" type="text" class="form-control" placeholder="Email">
        </div>

        <div class="form-group">
            <label for="phoneNumber">Número de telefono celular</label>
            <input id="form-checkout__phoneNumber" name="phoneNumber" type="number" class="form-control" placeholder="Número de telefono">
        </div>

        <div class="form-group">
            <label for="personType">Tipo de persona</label>
            <select id="form-checkout__personType" name="personType" type="email" class="form-control">
            <option value="natural">Natural</option>
            <option value="juridica">Jurídica</option>
            </select>
        </div>

        <div class="form-group">
            <label for="identificationType">Tipo de documento</label>
            <select id="form-checkout__identificationType" name="identificationType" type="text" class="form-control">
            </select>
        </div>

        <div class="form-group">
            <label for="identificationNumber">Número del documento</label>
            <input id="form-checkout__identificationNumber" name="identificationNumber" type="number" class="form-control" placeholder="Número de documento">
        </div>

        <div class="form-group">
            <div class="form-group">
                <label for="banksList">Banco</label>
                <div id="banksList"></div> 
            </div>
        </div>

        <div>
            <input type="hidden" name="transactionAmount" id="transactionAmount" value="100">
            <input type="hidden" name="description" id="description" value="Nome do Produto">
            <br>
            <button type="submit"  class="btn btn-primary">Pagar</button>
        </div>
    </form>
</div>
<div class="container mt-5">
    <p>Al ingresar sus datos usted acepta las<a href="https://www.pse.com/es/pages/privacy"> políticas de privacidad de PSE</a></p>
</div>
<script src="{{ url_for('static', filename='this_shit.js') }}"></script>
{% endblock %}

website/templates/tickets.html
{% extends "base.html" %}

{% block title %}
    Comprar Boleta
{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center" class="mt-5 mb-5">Registra tus datos</h3>
    <div class="form-group">
        <label for="email">
            Correo Electronico
        </label>
        <input 
            type="email" 
            class="form-control" 
            id="email" 
            name="email" 
            placeholder="Correo"
        />
    </div>

    <div class="form-group">
        <label for="name">
            Nombre Completo
        </label>
        <input 
            type="text" 
            class="form-control" 
            id="name" 
            name="name" 
            placeholder="Nombre Completo"
        />
    </div>

    <div class="form-group">
        <label for="contact">
            Numero de Celular
        </label>
        <input 
            type="number" 
            class="form-control" 
            id="contact" 
            name="contact" 
            placeholder="Celular"
        />
    </div>

    <div class="form-group">
        <label for="amount">
            Cantidad de boletas (maximo 20 boletas)
        </label>
        <input 
            type="number" 
            class="form-control" 
            id="amount" 
            name="amount" 
            min="1"
            max="20"
            placeholder="#"
        />
    </div>

    <br />
    <button type="submit" class="btn btn-primary">Comprar boleta</button>
</form>
{% endblock %}